openapi: "3.0.0"

info:
  title: Public transport
  version: "1.0.0"
  description: |
    An API for the public transport CRUD app.\
    All responses are wrapped in the envelop:
      - `statusCode` - integer value that represents HTTP response status code
      - `error` - (nullable) string value that represents error message
      - `data` - (nullable) value of specified schema type
  contact:
    email: r.m.khasanshin@gmail.com

tags:
  - name: Public transport

paths:
  /public_transport:
    get:
      tags:
        - Public transport
      summary: Get all public transport
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PublicTransport"
        "500":
          description: Unknown error
    post:
      tags:
        - Public transport
      summary: Add public transport
      requestBody:
        description: Add public transport request body
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddPublicTransportRequestBody"
      responses:
        "201":
          description: Success
          headers:
            Location:
              description: Added public transport URL (relative to API URL)
              schema:
                type: string
                example: /public_transport/12
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublicTransport"
        "500":
          description: Unknown error
  /public_transport/{id}:
    get:
      tags:
        - Public transport
      summary: Get public transport by ID
      parameters:
        - in: path
          name: id
          description: Public transport ID
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublicTransport"
        "404":
          description: Public transport is not found
        "500":
          description: Unknown error
    put:
      tags:
        - Public transport
      summary: Update public transport by ID
      parameters:
        - in: path
          name: id
          description: Public transport ID
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PublicTransport"
        "404":
          description: Public transport is not found
        "500":
          description: Unknown error
    delete:
      tags:
        - Public transport
      summary: Delete public transport by ID
      parameters:
        - in: path
          name: id
          description: Public transport ID
          required: true
          schema:
            type: integer
            minimum: 0
      responses:
        "204":
          description: Success
        "404":
          description: Public transport is not found
        "500":
          description: Unknown error

components:
  schemas:
    PublicTransport:
      type: object
      required:
        - id
        - type
        - route_number
        - capacity
        - organization_name
        - created_at
        - updated_at
      properties:
        id:
          type: number
          example: 12
        type:
          type: string
          example: bus
        route_number:
          type: string
          example: 32г
        capacity:
          type: number
          example: 50
        organization_name:
          type: string
          example: Пассажирское предприятие №8
        created_at:
          type: string
          example: "2020-09-21T08:41:28.000000Z"
        updated_at:
          type: string
          example: "2020-09-21T08:41:28.000000Z"
    AddPublicTransportRequestBody:
      type: object
      required:
        - type
        - route_number
        - capacity
        - organization_name
      properties:
        type:
          type: string
          example: bus
        route_number:
          type: string
          example: 32г
        capacity:
          type: number
          example: 50
        organization_name:
          type: string
          example: Пассажирское предприятие №8
